sudo: false
dist: bionic
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
env:
  - FLAGS=
  - FLAGS="--features static" ODBC_SYS_STATIC_PATH=/usr/lib/x86_64-linux-gnu/

script:
  - cargo build --verbose --all $FLAGS
  - cargo test --verbose --all $FLAGS
  - if [ "${ODBC_SYS_STATIC_PATH:-}" != "" ]; then
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
        if otool -L target/debug/examples/static_test | grep -q odbc; then
          echo Found non-static odbc ref!
          otool -L target/debug/examples/static_test
          exit 1
        fi
      else
        if ldd target/debug/examples/static_test | grep -q odbc; then
          echo Found non-static odbc ref!
          ldd target/debug/examples/static_test
          exit 1
        fi
      fi
    fi

matrix:
  allow_failures:
   - rust: nightly
  exclude:
   - os: osx
     rust: nightly
   - os: osx
     rust: beta
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    # FIXME: Workaround for https://travis-ci.community/t/syntax-error-unexpected-keyword-rescue-expecting-keyword-end-in-homebrew/5623/4
    HOMEBREW_NO_AUTO_UPDATE=1 brew install unixodbc
  fi
addons:
  apt:
    packages:
     - unixodbc
     - unixodbc-dev
services:
 - postgresql